version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src/FSharp.Formatting.Markdown"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/src/FSharp.Formatting.CodeFormat"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/src/FSharp.Formatting.ApiDocs"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/src/FSharp.Formatting.Literate"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/src/FSharp.Formatting.CSharpFormat"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/src/fsdocs-tool"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/src/FSharp.Formatting"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/src/FSharp.Formatting.Common"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/tests/FSharp.CodeFormat.Tests"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/tests/FSharp.Literate.Tests"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/tests/FSharp.Markdown.Tests"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/tests/FSharp.ApiDocs.Tests"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"

  - package-ecosystem: nuget
    directory: "/tests/FSharp.Formatting.TestHelpers"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "FSharp.Compiler.Service"
      - dependency-name: "Ionide.ProjInfo"
      - dependency-name: "Ionide.ProjInfo.Sln"
