version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 25
    ignore:
      - dependency-name: "Microsoft.Build"
      - dependency-name: "Microsoft.Build.Framework"
      - dependency-name: "Microsoft.Build.Utilities.Core"
      - dependency-name: "Microsoft.Build.Tasks.Core"
