language: csharp
sudo: required
dist: trusty # Ubuntu 14.04

addons:
  apt:
    packages:
      - libunwind8

before_install:
  - chmod +x build.sh

script:
  - ./build.sh

mono:
  - latest

branches:
  except:
    - gh-pages
    - release
