language: csharp
#sudo: required
sudo: false
dist: trusty # Ubuntu 14.04
mono: latest
dotnet : 2.0.0
addons:
  apt:
    packages:
      - libunwind8

before_install:
  - chmod +x build.sh

script:
  - ./build.sh


branches:
  except:
    - gh-pages
    - release
