language: csharp
sudo: false
dist: xenial
mono: latest
dotnet : 3.1.101
addons:
  apt:
    packages:
      - libunwind8
install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.7.2-api/

script:
 - ./build.sh
 
branches:
  except:
    - gh-pages
    - release
