os: linux
language: bash

services:
  - docker

script:
  - docker build -t fsharp-formatting-build .
  - docker run --rm fsharp-formatting-build ./build.sh -t All
 
branches:
  except:
    - gh-pages
    - release