image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
install:
  - cinst fake -pre

build_script:
  - cmd: build.cmd
after_build:
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

test: off

artifacts:
  - path: bin
    name: bin
nuget:
  account_feed: false
  project_feed: true
