image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
install:
  - cinst fake -pre

build_script:
  - cmd: build.cmd

test: off

artifacts:
  - path: bin
    name: bin
nuget:
  account_feed: false
  project_feed: true
