name: Build and Test PR

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Check code formatting conforms (run 'dotnet fantomas src tests docs build' to repair)
      run: dotnet fantomas src tests docs build --check
    - name: Build and test
      run: dotnet run --project ./build/build.fsproj
