name: Build and Test and Publish (main)

on:
  push:
    branches:
    - main

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Check code formatting conforms (run 'dotnet fantomas src tests docs build --recurse' to repair)
      run: dotnet fantomas src tests docs build -r --check
    - name: Build and test
      run: dotnet run --project ./build/build.fsproj
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
    - name: Publish NuGets (if main version changed)
      run: dotnet nuget push "artifacts/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.FSHARP_FORMATTING_TOKEN_2020 }} --skip-duplicate
